import java.time.LocalDateTime;
import java.util.ArrayList;


public class Message {
	private final User user;
	private String message;
	private final LocalDateTime time;

	public Message(User user, String message) {
		this.user = user;
		this.message = message;
		this.time = LocalDateTime.now();
	}

	public Message(User user, String message, LocalDateTime time) {
                this.user = user;
                this.message = message;
                this.time = time;
        }
    public void setMessage(String message) {
		this.message = message;
	}


	public User getUser() {
		return user;
	}

	public String getMessage() {
		return message;
	}

	public LocalDateTime getTime() {
		return time;
	}

	public String toString() { //follows this format: [userID|message|timeString]
		int userID = user.getID();
		String timeString = time.toString();
		return String.format("%s|%s|%s", userID, message, timeString);
	}

	public static Message fromString(String string) { //use with a string generated by toString()
		try {
			int firstSplit = string.indexOf("|");
			int secondSplit = string.lastIndexOf("|");
			String[] parts = {string.substring(0, firstSplit), string.substring(firstSplit + 1, secondSplit),
			string.substring(secondSplit + 1)};
			User user = User.getUserByID(Integer.parseInt(parts[0]));
			LocalDateTime time = LocalDateTime.parse(parts[2]);
			return new Message(user, parts[1], time);
		} catch (UserNotFoundException e) {
			e.printStackTrace();
			return null;
		}
	}
}
